apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.email }}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudDNS:
          project: "{{ .Values.project }}"
          serviceAccountSecretRef:
            name: "{{ .Values.serviceAccount }}"
            key: "{{ .Values.configKey }}"
