apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: admin-sa-secret
  annotations:
    kubernetes.io/service-account.name: admin-service-account
type: kubernetes.io/service-account-token
